steps:
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['install']
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'build']
  # We pinned this version to kill the "Retry Budget Exhausted" error
  - name: 'gcr.io/cloud-builders/firebase:3.12.0'
    args: ['deploy', '--project', 'aititrade-exchange-pro', '--only', 'hosting']

options:
  logging: CLOUD_LOGGING_ONLY
